[package]
name = "tdes"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_dispatch = "0.3.13"
lazy_static = "1.5.0"
ordered-float = "5.0.0"
priority-queue = "2.3.1"
tokio = { version = "1.45.0", features = ["full"] }
