experiments:
- name: empty_message
  scenario: simple_message
  topology:
    n_peers: 2
    name: twowaycustom
    connections:
      - [0, 1, !Full {bandwidth: 80000, latency: 0.04} ]
  extra_args:
    msg_size: 0
- name: 100_bytes_message
  scenario: simple_message
  topology:
    n_peers: 2
    name: twowaycustom
    connections:
      - [0, 1, !Full {bandwidth: 80000, latency: 0.04} ]
  extra_args:
    msg_size: 100
- name: distance_topology 
  scenario: simple_message
  arrival_time: distance
  topology:
    n_peers: 4
    name: twowaycustom
    connections:
      - [0, 1, !Bandwidth 80000]
      - [0, 2, !Bandwidth 80000]
      - [0, 3, !Bandwidth 80000]
    positions:
      - [0.0,         0.0,         ~]
      - [1142857.143, 0.0,         ~]
      - [0.0,         1142857.143, ~]
      - [1142857.143, 1142857.143, ~]
  extra_args:
    msg_size: 0
- name: star_topology 
  scenario: simple_message
  arrival_time: distance
  topology:
    n_peers: 5
    name: twowaycustom
    connections:
      - [0, 1, !Full {bandwidth: 80000, latency: 0.005} ]
      - [0, 2, !Full {bandwidth: 80000, latency: 0.02} ]
      - [0, 3, !Full {bandwidth: 80000, latency: 0.04} ]
      - [0, 4, !Full {bandwidth: 32000, latency: 0.04} ]
  extra_args:
    msg_size: 100
- name: flow_updating
  scenario: flow_updating_pairwise
  topology:
    n_peers: 7
    name: twowaycustom
    connections:
      - [0, 1, !Full {bandwidth: 80000, latency: 0.02} ]
      - [0, 2, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [0, 3, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [0, 4, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [0, 5, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [0, 6, !Full {bandwidth: 80000, latency: 0.02} ]
      - [1, 2, !Full {bandwidth: 80000, latency: 0.02} ]
      - [1, 3, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [1, 4, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [1, 5, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [1, 6, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [2, 3, !Full {bandwidth: 80000, latency: 0.02} ]
      - [2, 4, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [2, 5, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [2, 6, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [3, 4, !Full {bandwidth: 80000, latency: 0.02} ]
      - [3, 5, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [3, 6, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [4, 5, !Full {bandwidth: 80000, latency: 0.02} ]
      - [4, 6, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [5, 6, !Full {bandwidth: 80000, latency: 0.02} ]
  deadline: 1.75
  extra_args:
    values: [55, 72, 49, 30, 32, 49, 65]
- name: flow_updating_0_2
  scenario: flow_updating_pairwise
  topology:
    n_peers: 7
    name: twowaycustom
    connections:
      - [0, 1, !Full {bandwidth: 80000, latency: 0.02} ]
      - [0, 2, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [0, 3, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [0, 4, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [0, 5, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [0, 6, !Full {bandwidth: 80000, latency: 0.02} ]
      - [1, 2, !Full {bandwidth: 80000, latency: 0.02} ]
      - [1, 3, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [1, 4, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [1, 5, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [1, 6, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [2, 3, !Full {bandwidth: 80000, latency: 0.02} ]
      - [2, 4, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [2, 5, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [2, 6, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [3, 4, !Full {bandwidth: 80000, latency: 0.02} ]
      - [3, 5, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [3, 6, !Full {bandwidth: 80000, latency: 0.04768} ]
      - [4, 5, !Full {bandwidth: 80000, latency: 0.02} ]
      - [4, 6, !Full {bandwidth: 80000, latency: 0.03604} ]
      - [5, 6, !Full {bandwidth: 80000, latency: 0.02} ]
  deadline: 1.75
  drop_rate: 0.2
  extra_args:
    values: [55, 72, 49, 30, 32, 49, 65]
- name: flow_updating_manhattan
  scenario: flow_updating_pairwise
  topology:
    n_peers: 15
    name: twowaycustom
    connections:
      - [0, 1, !Full {bandwidth: 80000, latency: 0.02} ]
      - [1, 2, !Full {bandwidth: 80000, latency: 0.02} ]
      - [2, 3, !Full {bandwidth: 80000, latency: 0.02} ]
      - [3, 4, !Full {bandwidth: 80000, latency: 0.02} ]
      - [0, 5, !Full {bandwidth: 80000, latency: 0.02} ]
      - [1, 6, !Full {bandwidth: 80000, latency: 0.02} ]
      - [2, 7, !Full {bandwidth: 80000, latency: 0.02} ]
      - [3, 8, !Full {bandwidth: 80000, latency: 0.02} ]
      - [4, 9, !Full {bandwidth: 80000, latency: 0.02} ]
      - [5, 6, !Full {bandwidth: 80000, latency: 0.02} ]
      - [6, 7, !Full {bandwidth: 80000, latency: 0.02} ]
      - [7, 8, !Full {bandwidth: 80000, latency: 0.02} ]
      - [8, 9, !Full {bandwidth: 80000, latency: 0.02} ]
      - [5, 10, !Full {bandwidth: 80000, latency: 0.02} ]
      - [6, 11, !Full {bandwidth: 80000, latency: 0.02} ]
      - [7, 12, !Full {bandwidth: 80000, latency: 0.02} ]
      - [8, 13, !Full {bandwidth: 80000, latency: 0.02} ]
      - [9, 14, !Full {bandwidth: 80000, latency: 0.02} ]
      - [10, 11, !Full {bandwidth: 80000, latency: 0.02} ]
      - [11, 12, !Full {bandwidth: 80000, latency: 0.02} ]
      - [12, 13, !Full {bandwidth: 80000, latency: 0.02} ]
      - [13, 14, !Full {bandwidth: 80000, latency: 0.02} ]
  deadline: 2.0
  extra_args:
    values: [42, 86, 23, 50, 72, 95, 76, 58, 25, 51, 12, 66, 46, 37, 11]
